### PR TITLE
Some Updates

### PR DESCRIPTION
**Pull request by Dhruvacube**
I corrected the readme, you forgot to add await in example, plus removed py-cord dependency, because if that dependency is there then discord.py users like me  then monkeypatch the project!

### CODE REVIEW

**Comment by ankushKun** [comment]
@Dhruvacube Thank you for fixing the readme and adding `await`, I appreciate it.

> plus removed py-cord dependency, because if that dependency is there then discord.py users like me then monkeypatch the project!

Could you elaborate what you meant here? Did not get why you removed py-cord dependency as it is the maintained fork of discord.py and uses the same import statements.

**Comment by Dhruvacube** [comment]
Hey @ankushKun not all developers use pycord, there are many maintained versions of discord.py that came long ago even when original dpy was actively maintained! Like these https://github.com/iDevision/enhanced-discord.py https://github.com/StockerMC/discord.py , etc.

plus i see that you aren’t importing pycord anywhere in your module thus it should not be made dependancy, that is why you  should leave upto developers and state in the readme that your module requires discord namespace (this what jishkaku did https://github.com/Gorialis/jishaku#%EF%B8%8F-warning)

**Comment by ankushKun** [comment]
@Dhruvacube When I import discord it is using pycord, so it doesnot make sense when you say I never imported pycord in my code and should be removed.

```py
import discord
```
This imports discord stuff from py-cord smh

I can try what to make this into a cog, like jishaku, but until then I'm not removing anything from dependencies.

Thank you.

**Comment by Dhruvacube** [comment]
well, import discord statement isn't there anywhere in your code, plus what I was saying that there many maintained discord.py fork which haven't changed the namespace, so I was suggesting, instead of keeping pycord as a required dependency, keep the pycord as a optional dependency.
Well it seem you won't change the pycord to a optional dependency, so ig i will monkeypatch the project, which any lub can use which provide discord namespace!

**Comment by ankushKun** [comment]
wtf, yeah I didnot import Discord ugh, nvm sorry for that :p

Okay I can change py-cord to optional dependency

**Comment by Dhruvacube** [comment]
okay, then I am opening a another pr, this time i have optimized the code with some caching and memory efficient functions!

**Comment by ankushKun** [comment]
alright 👌

**Pull request closed without merging**
